### PR TITLE
fix: add prefix to en topics and email subscription

### PR DESCRIPTION
**Pull request by iamar7**
### Description

Added prefix to EN subscription email name & topic to make sure these property are unique.

Resolves: https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/issues/172

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content
This release add prefix to event notification subscription email name & topic to make sure these property are unique.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by akocbek — DISMISSED** [review]

**Comment by iamar7** [comment]
> @in-1911 Is this what you had in mind?

@ocofaigh this PR is making sure the topics and email subscription are unique when a user is provisioning multiple scc instance with the same event notification but this is not the fix for https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/issues/162 where `compliance` is added as a source by default in the EN instance. The provider needs to remove the hard coding for that issue and I have raised the provider issue [here](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5579).

**Comment by ocofaigh** [comment]
OK thanks, FYI, the error in the tests will be fixed in https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/pull/152/ so once thats merged, we can rebase this PR

**Comment by ocofaigh** [comment]
@iamar7 Hold off on this PR until we get https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/pull/182 merged

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
