### PR TITLE
Ask for cluster ID instead of name in agents DA

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

- cluster name may not be unique, and can give error like this:
  ```
   2024/11/25 16:08:59 Terraform plan | id: terraform-9ef4459f
   2024/11/25 16:08:59 Terraform plan | summary: '[ERROR] Error retrieving services bound to cluster: Request failed
   2024/11/25 16:08:59 Terraform plan | with
   2024/11/25 16:08:59 Terraform plan |   status code: 404, ServerErrorResponse: {"incidentID":"602b7f7c-6dca-4867-bcc1-befa20d5cde8","code":"G0008","description":"The
   2024/11/25 16:08:59 Terraform plan |   specified cluster could not be found by name. Provide the cluster ID instead.","type":"General","recoveryCLI":"To
   2024/11/25 16:08:59 Terraform plan |   list all clusters you have access to, run ''ibmcloud ks cluster ls''."}'
   2024/11/25 16:08:59 Terraform plan | severity: error
   2024/11/25 16:08:59 Terraform plan | resource: (Data) ibm_container_cluster
   2024/11/25 16:08:59 Terraform plan | operation: read
   2024/11/25 16:08:59 Terraform plan | component:
   2024/11/25 16:08:59 Terraform plan |   name: github.com/IBM-Cloud/terraform-provider-ibm
   2024/11/25 16:08:59 Terraform plan |   version: 1.71.2
  ```

    - Updating to use cluster ID. Also adding some custom pickers to the vars in ibm catalog manifest for better user experience.

- bumped ibm provider to 1.71.3 to pick up for fix https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5817

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
Tests are blocked due to https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5817

**Review by toddgiguere — DISMISSED** [review]

**Comment by ocofaigh** [comment]
This actually depends on a new SCC module version. Coming in https://github.com/terraform-ibm-modules/terraform-ibm-scc/pull/198

**Comment by ocofaigh** [comment]
The schematics test failed on destroy:
```
2024/11/26 22:28:02 Terraform refresh | Error: timeout while waiting for state to become 'normal' (last state: 'warning', timeout: 30m0s)
 2024/11/26 22:28:02 Terraform refresh | 
 2024/11/26 22:28:02 Terraform refresh |   with data.ibm_container_vpc_cluster.cluster[0],
 2024/11/26 22:28:02 Terraform refresh |   on provider.tf line 24, in data "ibm_container_vpc_cluster" "cluster":
 2024/11/26 22:28:02 Terraform refresh |   24: data "ibm_container_vpc_cluster" "cluster" {
```

Retrying..

**Comment by ocofaigh** [comment]
The test failed with:
```
        	Messages:   	Resource(s) identified to be updated 
        	            	Name: scc_instance_settings
        	            	Address: module.scc.ibm_scc_instance_settings.scc_instance_settings[0]
        	            	Actions: [update]
        	            	DIFF:
        	            	  Before: 
        	            		{"event_notifications":"SECURE_VALUE_HIDDEN_HASH:-433798ce3b7522209ff2148c34c38c91f071f179af9c6c89c5dda414"}
        	            	  After: 
        	            		{"event_notifications":"SECURE_VALUE_HIDDEN_HASH:-7099738d4ec3a8e7b93542f2aafa8fba2ab9ef8fc1b2da1f2f3ed7eb"}
```

I'm going to update to latest test wrapper version which is supposed to have a fix where the masking of non secure values is fixed..

**Comment by ocofaigh** [comment]
In the most recent I only skipped the agents test, and all other tests passed. I'll add it back in now just to ensure there is clash with the tests.

**Review by toddgiguere — APPROVED** [review]

**Pull request merged**
